return `<math>
 <mn>1</mn>
 <mo>+</mo>
 <munderover>
  <mo>&#x2211;</mo>
  <mrow>
   <msub><mi>𝑛</mi><mi>tabs</mi></msub>
   <mo>=</mo>
   <mn>1</mn>
  </mrow>
  <mi>${allSubjects.length}</mi>
 </munderover>
 <mrow>
  <mo>(</mo>
  <msub><mi>𝑛</mi><mi>tabs</mi></msub>
  <mo>+</mo>
  <mn>1</mn>
  <mo>)</mo>
  <msub><mi>𝑛</mi><mi>tabs</mi></msub>
  <mo>&#x00D7;</mo>
  <munderover>
   <mo>&#x220F;</mo>
   <mrow>
    <mi>i</mi>
    <mo>=</mo>
    <mn>1</mn>
   </mrow>
   <mrow>
    <msub><mi>𝑛</mi><mi>tabs</mi></msub>
   </mrow>
  </munderover>
  <mrow>
   <mo>(</mo>
   <mi>${allSubjects.length}</mi>
   <mo>-</mo>
   <mi>i</mi>
   <mo>-</mo>
   <mn>1</mn>
   <mo>)</mo>
  </mrow>
 </mrow>
</math>`