declare interface IMath
 extends IPart<ICore, IPartAny> {

 // Subparts.
 readonly vector: IVector

 // Components.
 /** Takes in two numbers and performs a traditional math modulo operation which handles negative numbers differently from the native `%` operator. */
 readonly mod(NUMBER_A: bigint, NUMBER_B: bigint): bigint
 readonly mod(NUMBER_A: number, NUMBER_B: number): number
 /** Takes in an array of terms and returns its total sum. */
 readonly sum(ARRAY: bigint[]): bigint
 readonly sum(ARRAY: number[]): number
 /** Provides an array (of length SIZE) of numbers representing the least significant bit of its indices. @remarks If `SIZE` is of the `bigint` type, the resulting array will contain only `bigint` values. If size is of the `number` type, the resulting array will contain only `number` values. */
 readonly createLSB(SIZE: bigint): bigint[]
 readonly createLSB(SIZE: number): number[]
 /** Creates a Fenwick tree which quickly finds the sum of an array of terms. It allows tweaking the value of individual terms without having to compute the entire sum again each time.
  * 
  * This can be used to performantly rank and unrank permutation indices where SIZE represents the cardinality of the superset from which the permutation will be chosen.
  * 
  * The Fenwick tree uses the `bigint` type rather than the `number` type. As such, the `SIZE` argument must be a BigInt.
  * 
  * The tree is initialized with a value of one for every term. */
 readonly createFenwickTree(SIZE: bigint): IFenwickTree<bigint>
 readonly createFenwickTree(SIZE: number): IFenwickTree<number>
 /** Returns the numeric constructor (either Number of Bigint) of the given number or throws and error if the input is neither. */
 readonly constructorOf(NUMBER: number): typeof Number
 /** Returns the numeric constructor (either Number of Bigint) of the given number or throws and error if the input is neither. */
 readonly constructorOf(NUMBER: bigint): typeof BigInt
 /** Clamps the given value to a value within the start and end range, inclusively. All arguments must be the same type. */
 readonly clamp<T extends number | bigint>(VALUE_TO_CLAMP: T, START_RANGE: T, END_RANGE: T): T

 // Properties.
 /** Equal to `2 * Math.PI` */
 readonly tau: number
 /** A cache of the least significant bit data generated by the `KMath.createLSB(...)` action. */
 readonly cachedLSB: LSBCache
}

declare interface LSBCache {
 get(key: typeof Number): number[]
 get(key: typeof BigInt): bigint[]
 set(key: typeof Number, value: number[]): this
 set(key: typeof BigInt, value: bigint[]): this
}

declare interface IFenwickTree<T = number | bigint> {
 /** Adds the value `value` to the term at `index`. */
 add(index: T, value: T): void
 /** Assigns the value `value` to the term at `index`. */
 set(index: T, value: T): void
 /** Removes the term at `index` (by setting it to 0). */
 remove(index: T): void
 /** Provides the partial sum of all terms up to and including the term at `lastIndex`. */
 partialSum(lastIndex: T): T
 /** Provides the sum of terms from `firstIndex` through `lastIndex`, inclusively. */
 sumOverRange(firstIndex: T, lastIndex: T): T
 /** Finds the index of the first term at which the partial sum (including that term) meets or exceeds `threshold`. Runs in O(log² n). If `assumeBinary` is `true`, uses a faster O(log n) binary lifting algorithm that is only accurate when all values in the tree are 0 or 1. */
 indexOfPartialSum(threshold: T, assumeBinary = true): T
}

/** Kireji Math
 * 
 * A library of math utilities not available on the native `Math` object. */
declare const KMath: IMath
type KMath = T